name: Waka Readme

on:
  schedule:
    # Runs at 12:30 AM UTC daily
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True" # Hide OS breakdown
          SHOW_PROJECTS: "False" # Hide projects worked on
          SHOW_LANGUAGE: "True" # Show languages breakdown
          SHOW_EDITORS: "True" # Show editors (VSCode, etc.)
          SHOW_COMMIT: "True" # Show commit activity
          SHOW_DAYS_OF_WEEK: "True" # Show productivity by day
          SHOW_SHORT_INFO: "True" # Show GitHub profile stats
          SHOW_PROFILE_VIEWS: "True" # Show profile views
          SHOW_TOTAL_CODE_TIME: "True" # Show total code time
          SHOW_UPDATED_DATE: "True" # Show last updated date
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          COMMIT_BY_ME: "True" # Commit with your user details
          COMMIT_MESSAGE: "chore: update dev metrics "
